[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/corazzon/finance-data-analysis/blob/main/4.3%20ETF%20%EB%B6%84%EC%84%9D%EA%B3%BC%20%EC%8B%9C%EA%B0%81%ED%99%94-input.ipynb)


## ETF 분석과 시각화

* keyword
    * seaborn - barplot, boxplot, violinplot
    * **seaborn PairGrid vs matplotlib - subplots**
    * seaborn FacetGrid
        * **catplot 범주형 데이터 시각화 (kind: count, bar, box, boxen, violin)**
        * relplot 연속된 수치 데이터 시각화 (kind: scatter, line) <= KRX 전체 종목 분석에서 다룸
    * pandas - value_counts, cross_tab, groupby, pivot_table
  
<img src="https://seaborn.pydata.org/_images/function_overview_8_0.png">

* seaborn 에 대해 좀 더 알고 싶다면 다음의 튜토리얼을 참고해 보세요.
* [User guide and tutorial — seaborn documentation](https://seaborn.pydata.org/tutorial.html)



* 특정 시점의 데이터를 저장해 분석합니다.
* 분석하는 시점에 따라 내용이 달라지는 점에 유의하세요!
* 내가 수집한 시점의 데이터를 분석하기 때문에 매일 분석한다면 일자별 리포트를 만들어 볼 수도 있을거에요.
* [ETF : 네이버 금융](https://finance.naver.com/sise/etf.nhn)


## ⚠️ 주의사항 ⚠️ 
*  분석내용은 데이터 수집 시점에 따라 달라집니다.

## 라이브러리 로드

In [ ]:
# 필요한 도구를 로드합니다.
# 데이터 분석을 위한 pandas, 수치계산을 위한 numpy, 시각화를 위한 seaborn, matplotlib


In [ ]:
# seaborn 의 버전을 확인합니다. 
# 0.11.0 이상의 버전에서 변경된 내용이 많으니 0.11 이상의 버전을 사용해 주세요.
sns.__version__

In [ ]:
pd.__version__

## 시각화를 위한 한글폰트 설정

In [ ]:
def get_font_family():
    """
    시스템 환경에 따른 기본 폰트명을 반환하는 함수
    """
    import platform
    system_name = platform.system()
    # colab 사용자는 system_name이 'Linux'로 확인

    if system_name == "Darwin" :
        font_family = "AppleGothic"
    elif system_name == "Windows":
        font_family = "Malgun Gothic"
    else:
        !apt-get install fonts-nanum -qq  > /dev/null
        !fc-cache -fv

        import matplotlib as mpl
        mpl.font_manager._rebuild()
        findfont = mpl.font_manager.fontManager.findfont
        mpl.font_manager.findfont = findfont
        mpl.backends.backend_agg.findfont = findfont
        
        font_family = "NanumBarunGothic"
    return font_family

In [ ]:
# 사용가능한 그래프 스타일
print(plt.style.available)

In [ ]:
# 운영체제에 맞는 font_family 찾기 


In [ ]:
# 그래프 스타일 설정
# plt.style.use("fivethirtyeight")
# plt.style.use("bmh")

# dark mode 사용자를 위한 스타일 추천
# plt.style.use("dark_background")


# 폰트설정

# 마이너스폰트 설정

# 그래프에 retina display 적용


In [ ]:
# 한글폰트 확인


## 데이터 로드

In [ ]:
# 이전 수업에서 수집해서 저장해둔 csv 파일을 읽어옵니다.
# itemcode 숫자 앞의 0 이 지워진다면 
# dtype={"종목코드": np.object} 로 타입을 지정해 주면 문자형태로 읽어옵니다.
# df


In [ ]:
# 인덱스 번호 상단 5개의 데이터를 가져옵니다.
# 제대로 read되었는지 각 column정보들을 확인합니다.


In [ ]:
# 인덱스 하단의 5개 데이터를 가져옵니다.
# 데이터가 제대로 로드되었는지 확인합니다.


In [ ]:
# info를 통해서 각 column들의 데이터타입과 결측치, 메모리 사용량 등을 볼 수 있습니다.


## 결측치 확인

In [ ]:
(True + True + False) / 3

In [ ]:
# 결측치를 확인합니다.


In [ ]:
# 결측치의 비율을 봅니다.


In [ ]:
# heatmap을 통한 결측치 시각화


## 범주형 데이터의 빈도수
### 범주형 변수 찾기

In [ ]:
# describe를 통해 범주형 변수에 대한 기술통계 값을 구하기


In [ ]:
# unique(중복을 제외한 값)에 대한 빈도수 구하기
# object type 이 아니더라도 nunique 값이 작다면 범주형 변수인지 확인해 봅니다.


### ETF 상품 유형별 빈도수(한 개의 변수)

In [ ]:
# df["유형"].value_counts() 의 결과와 같게 시각화 할 수 있습니다.


In [ ]:
# sns.countplot 으로 빈도수를 시각화 합니다.


In [ ]:
# value_counts 로 빈도수를 직접 계산합니다.


In [ ]:
# value_counts(normalize=True) 로 빈도수의 비율을 구합니다.


### 두 개의 변수 빈도수와 비율

In [ ]:
# 유형 컬럼의 빈도수를 봅니다.
# seaborn countplot의 hue를 이용하여 인버스여부에 따라 다른 색상으로 표시해 봅니다.


In [ ]:
# pandas crosstab을 이용하여 위 그래프의 수치를 확인 할 수 있습니다.
# seaborn 은 아래와 같은 연산을 하지 않더라도 알아서 통계적 연산을 시각화 해줍니다.


In [ ]:
# value_counts 처럼 normalize 를 사용해 비율을 구할 수도 있습니다.


In [ ]:
# 동일하게 유형 데이터를 레버리지 여부에 따라 그립니다.


In [ ]:
# 레버리지, 유형에 대한 빈도수를 구힙니다.


In [ ]:
# 레버리지, 유형에 대한 빈도수의 비율을 구합니다.


### 브랜드별 빈도수

In [ ]:
# 브랜드별 ETF 빈도수


### 인버스, 브랜드의 ETF 빈도 비율


* 인버스 ETF란? 주식관련 장내 외 파생상품 투자 및 증권차입매도 등을 통해 기초지수(KOSPI 200지수)의 일일 변동률(일별수익률)을 음의 1배수 즉, 역방향으로 추적하는 ETF를 말한다. 예를 들어, KOSPI 200지수가 1% 상승할 경우 인버스 ETF는 마이너스 1% 수익률, 반대로 KOSPI 200 지수가 1% 하락시 인버스 ETF는 플러스 1%의 수익률을 목표로 운영된다.
[네이버 지식백과] 인버스ETF (매일경제, 매경닷컴)
* 출처 : https://terms.naver.com/entry.nhn?docId=20336&cid=43659&categoryId=43659

In [ ]:
# 브랜드 column의 빈도수를 인버스에 따른 구분으로 그려봅니다.


In [ ]:
# 인버스, 브랜드의 금융상품 빈도수


In [ ]:
# 인버스, 브랜드의 금융상품 빈도 비율
# in_brand_norm


### 레버리지, 브랜드의 ETF 빈도 비율
* 레버리지 ETF란? 일반 ETF가 코스피200과 같은 지수 내 대표 주식을 보유함으로써 지수와 비슷한 수익률을 내는 것을 목표로 하는 데 비해 레버리지ETF는 선물 등 파생상품에 투자해 지수보다 높은 수익을 추구하는 ETF다. 상승장에서는 높은 수익률을 기대할 수 있지만 하락장에서는 손실도 커져 고위험ㆍ고수익 상품으로 분류된다.
[네이버 지식백과] 레버리지 ETF (매일경제, 매경닷컴)
* 출처 : https://terms.naver.com/entry.nhn?docId=2059802&cid=43659&categoryId=43659

In [ ]:
# 브랜드별 레버리지 여부에 따른 빈도수를 시각화 합니다.


In [ ]:
# 레버리지, 브랜드의 ETF 빈도수(crosstab)


In [ ]:
# 레버리지, 브랜드의 ETF 빈도수(crosstab)


In [ ]:
# 레버리지, 브랜드의 ETF 비율


## 수치형 변수의 기술통계

In [ ]:
# describe로 수치형 변수의 기술통계 구하기
# desc


## 수치형 변수로 히스토그램 그리기

* 연속된 수치 데이터를 범주형 데이터로 표현, bucketing 이라고 부르기도 함
* 히스토그램 : 도수분포를 그래프 형태로 표현한 것
* 막대그래프와 비슷해 보이지만 다른 그래프
* 참고 : [히스토그램 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%ED%9E%88%EC%8A%A4%ED%86%A0%EA%B7%B8%EB%9E%A8)

In [ ]:
# 수치형 컬럼만 리스트로 만들기
# num_cols


In [ ]:
# 히스토그램을 그려보면 수치 데이터로 되어있지만 범주형 데이터를 찾아볼 수 있습니다.


## 범주형 vs 수치형 변수
### seaborn의 barplot 이해하기

In [ ]:
# seaborn의 bar chart를 이용하여 각 브랜드에 대한 3개월수익률의 평균값을 볼 수 있습니다.
# 검은색 막대는 ci로 신뢰구간을 의미합니다.


### barplot 그래프의 값을 groupby 로 직접 구하기

In [ ]:
# 위 그래프의 평균 값을 직접 계산을 통해 구해 봅니다.
# brand_3month_mean


In [ ]:
# 위에서 구한 그룹(브랜드)별 평균 3개월 수익률을 그래프로 표현합니다.


In [ ]:
# 브랜드가 마이티인 경우의 데이터를 확인합니다.


In [ ]:
# 브랜드 대비 3개월수익률에 대한 정보를 레버리지 값의 차이를 barplot으로 봅니다.
# 레버리지 유/무에 따라서 평균 3개월 수익률은 많은 차이가 없지만,
# 표준편차의 경우 레버리지가 있을경우 굉장히 편차(ci="sd")가 심함을 알 수 있습니다.
# 레버리지 상품은 오를 때 더 많이 오르고 내릴 때 더 많이 내립니다.


* [Styling — pandas documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html)

In [ ]:
# 위에서 그린 그래프의 값을 groupby로 구합니다.


### boxplot으로 그리기

#### 기술통계 용어

* 백분위 수 : 데이터를 백등분 한 것
* 사분위 수 : 데이터를 4등분 한 것
* 중위수 : 데이터의 정 가운데 순위에 해당하는 값.(관측치의 절반은 크거나 같고 나머지 절반은 작거나 같다.)
* 제 3사분위 수 (Q3) : 중앙값 기준으로 상위 50% 중의 중앙값, 전체 데이터 중 상위 25%에 해당하는 값
* 제 1사분위 수 (Q1) : 중앙값 기준으로 하위 50% 중의 중앙값, 전체 데이터 중 하위 25%에 해당하는 값
* 사분위 범위 수(IQR) : 데이터의 중간 50% (Q3 - Q1)

* 출처 : [상자 수염 그림 - 위키백과, 우리 모두의 백과사전](https://ko.wikipedia.org/wiki/%EC%83%81%EC%9E%90_%EC%88%98%EC%97%BC_%EA%B7%B8%EB%A6%BC)

In [ ]:
# 브랜드별 3개월 수익률을 레버리지에 따라 다른 색상으로 시각화 합니다.


#### boxplot 보는 방법

* 사분위수 범위(IQR, Interquartile range, Q3-Q1)
* 이상치를 제외한 최댓값  = Q3 + 1.5IQR
* 이상치를 제외한 최솟값  = Q1 - 1.5IQR

### 3개월 수익률에 대한 기술통계 값 구하기

In [ ]:
# 위에서 그린 boxplot의 값을 직접 구해봅니다.
# brand_3month_desc


<img src="https://miro.medium.com/max/1400/1*NRlqiZGQdsIyAu0KzP7LaQ.png" width="400">

* 이미지 출처 : https://towardsdatascience.com/understanding-boxplots-5e2df7bcbd51

### KODEX ETF 따로 분석하기

* ⚠️ 주의사항 ⚠️  분석내용은 데이터 수집 시점에 따라 달라집니다.

In [ ]:
# KODEX 서브셋을 만듭니다.


In [ ]:
# KODEX 의 boxplot을 그립니다.


In [ ]:
# KODEX 의 boxenplot을 그립니다.


In [ ]:
# KODEX 의 historam 을 pandas로 그립니다.


In [ ]:
# KODEX 의 kdeplot 을 그립니다.


In [ ]:
# KODEX 의 violinplot 을 그립니다.


In [ ]:
# KODEX 의 violinplot 에 hue="레버리지"로 그립니다.


In [ ]:
# KODEX 의 violinplot 에 hue="레버리지"를 split 옵션을 사용해 그립니다.


In [ ]:
# KODEX 의 violinplot 에 hue="인버스"로 그립니다.


* 이미지 출처 : [The Datasaurus Dozen - Same Stats, Different Graphs | Autodesk Research](https://www.autodeskresearch.com/publications/samestats)

<img src="https://d2f99xq7vri1nk.cloudfront.net/BoxViolinSmaller.gif">

### 브랜드별 3개월수익률

In [ ]:
# boxenplot 을 통해 브랜드별 3개월 수익률을 시각화 합니다.


In [ ]:
# violinplot은 kdeplot을 마주보도록 그린 그래프로 값의 분포를 알 수 있습니다.
# boxplot의 단점을 보완하기 위해 만들어지기도 했는데 내부에 boxplot을 함께 그려줍니다.
# 가운데 점은 중앙값을 의미합니다.


### 서브플롯 그려보기

In [ ]:
# boxplot과 violinplot을 하나의 그래프에 같이 그려봅니다.


In [ ]:
# violinplot은 kdeplot을 마주보도록 그린 그래프로 값의 분포를 알 수 있습니다.
# boxplot의 단점을 보완하기 위해 만들어지기도 했는데 내부에 boxplot을 함께 그려줍니다.
# 가운데 점은 중앙값을 의미합니다.
# 브랜드별 3개월수익률을 레버리지 여부에 따라 그려봅니다.


In [ ]:
# 브랜드별 3개월수익률을 인버스 여부에 따라 그려봅니다.


### 브랜드별 거래량

In [ ]:
# 수집한 날짜에 대한 브랜드별 거래량을 봅니다.


In [ ]:
# df[df["브랜드"].isin(["TIGER", "KBSTAR", "KINDEX"])]

In [ ]:
# 전체 브랜드를 보면 값의 크기 차이로 시각화를 제대로 보기 어렵습니다.
# 일부 브랜드 "TIGER", "KBSTAR", "KINDEX" 를 따로 가져와서 시각화 합니다.


In [ ]:
# "마이티", "마이다스", "흥국" 만 봅니다.


In [ ]:
# "마이티", "마이다스", "흥국" 의 기술통계 값 보기


### 유형에 따른 거래량

In [ ]:
# 유형에 따른 평균 거래량을 barplot으로 시각화 합니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 거래량을 직접 groupby를 통해 구합니다.


### 유형에 따른 거래대금

In [ ]:
# 위 그래프의 유형에 따른 평균 거래대금(백만)을 barplot 으로 그립니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 거래대금(백만)을 직접 groupby를 통해 구합니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 거래대금(백만)을 직접 pivot_table을 통해 구합니다.


### 유형에 따른 시가총액

In [ ]:
# 유형에 따른 평균 시가총액(억) 에 대한 시각화를 합니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 시가총액(억)을 직접 groupby를 통해 구합니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 시가총액(억)을 직접 pivot_table을 통해 구합니다.


### 유형에 따른 3개월 수익률

In [ ]:
# 유형에 따른 평균 3개월수익률에 대한 시각화를 합니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 3개월수익률을 직접 groupby를 통해 구합니다.


In [ ]:
# 위 그래프의 유형에 따른 평균 3개월수익률을 직접 pivot_table을 통해 구합니다.


## 여러 개의 변수로 서브플롯 그리기
### PairGrid와 barplot 으로 서브플롯 그리기


* PairGrid는 한번에 서브플롯을 쉽게 그려볼 수 있는 장점이 있지만 아쉽게도 share axis in PairGrid는 지원하지 않고 있습니다.
* 참고 : https://github.com/mwaskom/seaborn/issues/1032

In [ ]:
# PairGrid 와 barplot을 한번에 서브플롯으로 그립니다.
# 유형에 따른 "거래량", "거래대금(백만)", "시가총액(억)", "3개월수익률" 에 대한 시각화를 합니다.


### subplots를 통한 시각화

In [ ]:
row_cols = ["거래량", "거래대금(백만)", "시가총액(억)", "3개월수익률"]

In [ ]:
# 위 그래프를 직접 subplots 를 사용해 그려봅니다.


In [ ]:
# 브랜드별 수치 데이터의 평균을 시각화 합니다.


### 브랜드별 인버스 여부에 따른 시각화

In [ ]:
# subplots를 시각화 합니다. hue="인버스"를 적용해 봅니다.


### 브랜드별 레버리지 여부에 따른 시각화

In [ ]:
# subplots를 시각화 합니다. hue="레버리지"를 적용해 봅니다.


In [ ]:
# 위에서 그린 서브플롯을 직접 groupby 로 구해봅니다.


### 유형에 따른 3개월 수익률 boxplot 
* barplot으로 그렸을 때 보이지 않던 데이터의 빈도수와 데이터의 분포를 확인할 수 있습니다.


In [ ]:
# boxplot 으로 x축에 "유형" y축에 "3개월수익률" 을 그려봅니다.


In [ ]:
# boxplot의 유형에 따른 3개월 수익률에 대한 기술통계 값을 구합니다.


### subplots 로 유형에 대한 boxplot 그리기

In [ ]:
# subplots 를 통한 유형에 따른 수치데이터의 평균값 구하기


In [ ]:
# hue="레버리지" 를 추가해서 그립니다.


### subplots 로 유형에 대한  violinplot 그리기
* boxplot으로 그렸을 때 박스 안의 분포를 좀 더 자세히 그려줍니다.

In [ ]:
# 유형에 따른 violinplot 


In [ ]:
# 유형에 따른 violinplot 에 hue="레버리지" 적용하기


### PairGrid 를 통해 여러 변수의 violinplot 그리기

In [ ]:
# 브랜드에 따른 여러 수치변수의 violinplot 를 PairGrid로 그리기


### subplots 로 브랜드에 대한 boxplot 그리기

In [ ]:
# 브랜드에 따른 여러 수치변수의 boxplot 을 subplots으로 그리기 : hue="레버리지"


### subplots 로 브랜드에 대한 violinplot 그리기

In [ ]:
# 브랜드에 따른 여러 수치변수의 violinplot 을 subplots으로 그리기 : hue="레버리지"



## FacetGrid 를 통한 범주형 변수에 대한 서브플롯 그리기

In [ ]:
# catplot 을 통한 브랜드별 3개월 수익률


In [ ]:
# catplot 을 통한 브랜드별 3개월 수익률 : kind="bar"


In [ ]:
# catplot 을 통한 브랜드별 3개월 수익률 : kind="box"


In [ ]:
# catplot 을 통한 브랜드별 3개월 수익률 : kind="violin"


### 특정 범주형 변수에 대한 서브플롯 그리기 - catplot
#### 브랜드 별 빈도수 - countplot

#### 브랜드별 3개월 수익률 - barplot

#### 브랜드별 거래량 - barplot

## 해외 주식 ETF

In [ ]:
# 유형이 "해외 주식"인 ETF만 가져옵니다.
# oversea


In [ ]:
# "해외 주식"ETF의 브랜드별 "3개월수익률"을 시각화 합니다.


In [ ]:
# "해외 주식"ETF의 브랜드별 평균 "3개월수익률"을 hue="환헤지H"로 시각화 합니다.


In [ ]:
# "해외 주식"ETF의 브랜드별 평균 "3개월수익률"을 violinplot으로 시각화 합니다.


In [ ]:
# 위에서 그린 그래프를 catplot을 통해 그리며  col="레버리지", row="인버스"로 시각화 합니다.



## 상관분석

상관 분석(相關 分析, Correlation analysis) 또는 '상관관계' 또는 '상관'은 확률론과 통계학에서 두 변수간에 어떤 선형적 또는 비선형적 관계를 갖고 있는지를 분석하는 방법이다. 두 변수는 서로 독립적인 관계이거나 상관된 관계일 수 있으며 이때 두 변수간의 관계의 강도를 상관관계(Correlation, Correlation coefficient)라 한다. 상관분석에서는 상관관계의 정도를 나타내는 단위로 모상관계수로 ρ를 사용하며 표본 상관 계수로 r 을 사용한다.

상관관계의 정도를 파악하는 상관 계수(相關係數, Correlation coefficient)는 두 변수간의 연관된 정도를 나타낼 뿐 인과관계를 설명하는 것은 아니다. 두 변수간에 원인과 결과의 인과관계가 있는지에 대한 것은 회귀분석을 통해 인과관계의 방향, 정도와 수학적 모델을 확인해 볼 수 있다.

* 출처 : https://ko.wikipedia.org/wiki/%EC%83%81%EA%B4%80_%EB%B6%84%EC%84%9D

### 피어슨 상관계수

* r 값은 X 와 Y 가 완전히 동일하면 +1, 전혀 다르면 0, 반대방향으로 완전히 동일 하면 –1 을 가진다. 
* 결정계수(coefficient of determination)는 r^2 로 계산하며 이것은 X 로부터 Y 를 예측할 수 있는 정도를 의미한다.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Correlation_examples2.svg/800px-Correlation_examples2.svg.png" width="500">

```
일반적으로
r이 -1.0과 -0.7 사이이면, 강한 음적 선형관계,
r이 -0.7과 -0.3 사이이면, 뚜렷한 음적 선형관계,
r이 -0.3과 -0.1 사이이면, 약한 음적 선형관계,
r이 -0.1과 +0.1 사이이면, 거의 무시될 수 있는 선형관계,
r이 +0.1과 +0.3 사이이면, 약한 양적 선형관계,
r이 +0.3과 +0.7 사이이면, 뚜렷한 양적 선형관계,
r이 +0.7과 +1.0 사이이면, 강한 양적 선형관계
```

<img src="https://upload.wikimedia.org/wikipedia/commons/3/34/Correlation_coefficient.png" width=500>

* 출처 :  https://ko.wikipedia.org/wiki/%EC%83%81%EA%B4%80_%EB%B6%84%EC%84%9D#%ED%94%BC%EC%96%B4%EC%8A%A8_%EC%83%81%EA%B4%80_%EA%B3%84%EC%88%98



### 상관계수 구하기

In [ ]:
# 전체 데이터프레임에 대한 상관계수를 구합니다.
# corr


In [ ]:
# np.triu : matrix를 상삼각행렬로 만드는 numpy math
# [1 2 3]   np.triu  [1 2 3]
# [4 5 6]   -------> [0 5 6]
# [2 3 4]            [0 0 4]
# np.ones_like(x) : x와 크기만 같은 1로 이루어진 array를 만듬

# 수식적으로 어려워 보일수도 있지만 간단함
# 자기상관계수는 대각행렬을 기준으로 대칭되어 같은 값이 출력되므로,
# 이대로 전체를 heatmap을 plot하면 오히려 가독성이 떨어질 수 있음
# 이에, 가독성을 높이기 위해 대각행렬 기준으로 한쪽의 데이터들만 masking 기법을 통해 plot하여 
# 가독성을 높이는 효과를 가질수 있음
# np.ones_like로 heatmap의 마스크값 구하기
mask = np.triu(np.ones_like(corr))

In [ ]:
# seaborn 의 heatmap으로 상관 계수 시각화 하기


### 양 혹은 음의 상관 계수가 높은 변수끼리의 regplot 그리기

In [ ]:
# regplot을 통해 양의 상관 계수가 높은 변수끼리 시각화 합니다.


In [ ]:
# regplot을 통해 음의 상관 계수가 높은 변수끼리 시각화 합니다.


### 종목별 상관 계수

In [ ]:
# select_dtypes 를 통해 object 타입을 제외한 타입을 제외하고 가져오록 합니다.
# 종목명을 인덱스로 만들어 줍니다.
# df_num


In [ ]:
# transpose 로 행과 열을 바꿉니다.
# df_t

In [ ]:
# df_t의 데이터 타입을 float 으로 변경하고 상관 계수 구하기
# etf_corr

* "KODEX 200" 과 상관계수가 높은 ETF 상위 10개

In [ ]:
# "KODEX 200" 과 상관계수가 높은 ETF 상위 10개


* "KODEX 200" 과 상관계수가 낮은 ETF 하위 10개

In [ ]:
# "KODEX 200" 과 상관계수가 낮은 ETF 하위 10개


### 2X ETF의 상관계수

In [ ]:
# 2X가 들어가는 ETF의 상관 계수만 가져오기
# etf_corr_2x


In [ ]:
# np.ones_like로 heatmap의 마스크값 구하기
# mask_2x


In [ ]:
# seaborn 의 heatmap으로 상관 계수 시각화 하기


### 원유와 관련된 ETF의 상관계수 보기

In [ ]:
# 원유가 들어가는 상관계수만 가져오기
# etf_corr_oil

In [ ]:
# np.ones_like로 heatmap의 마스크값 구하기
# mask_oil

In [ ]:
# seaborn 의 heatmap으로 상관 계수 시각화 하기


## seaborn 공식문서

* seaborn 에 대해 좀 더 알고 싶다면 다음의 튜토리얼을 참고해 보세요.
* [User guide and tutorial — seaborn documentation](https://seaborn.pydata.org/tutorial.html)